apiVersion: v1
kind: Service
metadata:
  name: springapp
  namespace: prac-ns
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc 
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017

