apiVersion: v1
kind: Service
metadata:
  name: springappsvc
  namespace: prac-ns
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: prac-ns 
spec:
  selector:
    app: mongodb 
  ports:
  - port: 27017
    targetPort: 27017

